# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170724_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getdata',
            name='data',
        ),
        migrations.AddField(
            model_name='getdata',
            name='data1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='getdata',
            name='data10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='getdata',
            name='data11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='getdata',
            name='data12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='getdata',
            name='data2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='getdata',
            name='data3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='getdata',
            name='data4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='getdata',
            name='data5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='getdata',
            name='data6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='getdata',
            name='data7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='getdata',
            name='data8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='getdata',
            name='data9',
            field=models.IntegerField(default=0),
        ),
    ]
